# build modules
FROM node:16 AS stage1
WORKDIR /app
COPY package*.json ./
RUN npm ic

FROM node:16-alpine
WORKDIR /app
COPY --from=stage1 /app/node_modules /app/node_modules

CMD [ "npm", "run", "dev" ]