FROM node:14 AS builder
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ic

COPY . .
RUN npx pkg --targets node14-alpine-x64 -o nodeappbin .

FROM amd64/alpine
COPY --from=builder /usr/src/app/nodeappbin /nodeappbin

ENTRYPOINT /nodeappbin