# build modules
FROM node:14 AS step0
WORKDIR /app
COPY package*.json ./
RUN npm ic
COPY . .
RUN npm run build

# last stage
FROM amd64/alpine
WORKDIR /
COPY --from=step0 /app/dockerizenodeapp /app/app.bin

CMD /app/app.bin